export CUDA_VISIBLE_DEVICES=0,1

model_name=TimesNet_stft

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --conv_layers 6 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --d_model 8 \
  --d_ff 16 \
  --des 'Exp' \
  --itr 1 \
  --n_fft 8 \
  --win_len 8 \
  --batch_size 16 \
  --train_epochs 6 \
  --learning_rate 0.00001

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --conv_layers 6 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --d_model 8 \
  --d_ff 16 \
  --des 'Exp' \
  --itr 1\
  --n_fft 8 \
  --win_len 8 \
  --batch_size 16 \
  --train_epochs 5 \
  --learning_rate 0.00001

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --conv_layers 6 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --d_model 8 \
  --d_ff 16 \
  --des 'Exp' \
  --itr 1 \
  --n_fft 8 \
  --win_len 8 \
  --batch_size 16 \
  --train_epochs 40 \
  --learning_rate 0.00001

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --conv_layers 6 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --d_model 8 \
  --d_ff 16 \
  --des 'Exp' \
  --itr 1 \
  --n_fft 8 \
  --win_len 8 \
  --batch_size 16 \
  --train_epochs 3 \
  --learning_rate 0.00001
