export CUDA_VISIBLE_DEVICES=1,0

model_name=SpecAR_Net

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_96_96 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1\
  --d_layers 1 \
  --conv_layers 6 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 16 \
  --d_ff 16 \
  --itr 1 \
  --n_fft 8 \
  --win_len 8 \
  --win_func rectangle \
  --hop_length 1\
  --batch_size 64 \
  --learning_rate 0.0001 \
  --train_epochs 20

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_96_192 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --conv_layers 6 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 16 \
  --d_ff 16 \
  --itr 1 \
  --n_fft 8 \
  --win_len 8 \
  --win_func rectangle \
  --hop_length 1\
  --batch_size 64 \
  --learning_rate 0.0001 \
  --train_epochs 20

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_96_336 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --conv_layers 6 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 16 \
  --d_ff 16 \
  --itr 1 \
  --n_fft 8 \
  --win_len 8 \
  --win_func rectangle \
  --hop_length 1\
  --batch_size 64 \
  --learning_rate 0.0001 \
  --train_epochs 20

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_96_720 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --d_layers 1 \
  --conv_layers 6 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 16 \
  --d_ff 16 \
  --itr 1 \
  --n_fft 8 \
  --win_len 8 \
  --win_func rectangle \
  --hop_length 1\
  --batch_size 64 \
  --learning_rate 0.0001 \
  --train_epochs 20

